/********************************************************************************
** Form generated from reading UI file 'cmbverify.ui'
**
** Created by: Qt User Interface Compiler version 4.8.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CMBVERIFY_H
#define UI_CMBVERIFY_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_CmbVerifyClass
{
public:
    QLabel *label_208;
    QPushButton *btnPara;
    QPushButton *btnExit;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QFrame *frame;
    QLabel *label;
    QGroupBox *groupBox;
    QRadioButton *rbtn_pos_in;
    QRadioButton *rbtn_pos_out;
    QGroupBox *groupBox_2;
    QRadioButton *rbtn_unit_kwh;
    QRadioButton *rbtn_unit_mj;
    QGroupBox *groupBox_3;
    QLabel *label_2;
    QLabel *label_3;
    QLineEdit *lineEdit_min_theta;
    QGroupBox *groupBox_4;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *lineEdit_std_in_r;
    QPushButton *btn_collection;
    QPushButton *btn_stop;
    QLabel *label_6;
    QLineEdit *lineEdit_std_in_t;
    QLabel *label_7;
    QLineEdit *lineEdit_std_out_t;
    QLabel *label_8;
    QLineEdit *lineEdit_std_out_r;
    QLabel *label_9;
    QGroupBox *gbox_meter_1;
    QLabel *label_10;
    QLineEdit *lineEdit_sn_1;
    QLineEdit *lineEdit_e0_1;
    QLabel *label_11;
    QLineEdit *lineEdit_v0_1;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *lineEdit_e1_1;
    QLabel *label_19;
    QLineEdit *lineEdit_v1_1;
    QLabel *label_14;
    QLineEdit *lineEdit_err_1;
    QLabel *label_15;
    QLabel *label_20;
    QGroupBox *gbox_meter_2;
    QLabel *label_21;
    QLineEdit *lineEdit_sn_2;
    QLineEdit *lineEdit_e0_2;
    QLabel *label_22;
    QLineEdit *lineEdit_v0_2;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLineEdit *lineEdit_e1_2;
    QLabel *label_28;
    QLineEdit *lineEdit_v1_2;
    QLabel *label_29;
    QLineEdit *lineEdit_err_2;
    QLabel *label_30;
    QLabel *label_31;
    QGroupBox *gbox_meter_3;
    QLabel *label_32;
    QLineEdit *lineEdit_sn_3;
    QLineEdit *lineEdit_e0_3;
    QLabel *label_33;
    QLineEdit *lineEdit_v0_3;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLineEdit *lineEdit_e1_3;
    QLabel *label_39;
    QLineEdit *lineEdit_v1_3;
    QLabel *label_40;
    QLineEdit *lineEdit_err_3;
    QLabel *label_41;
    QLabel *label_42;
    QGroupBox *gbox_meter_4;
    QLabel *label_43;
    QLineEdit *lineEdit_sn_4;
    QLineEdit *lineEdit_e0_4;
    QLabel *label_44;
    QLineEdit *lineEdit_v0_4;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLabel *label_49;
    QLineEdit *lineEdit_e1_4;
    QLabel *label_50;
    QLineEdit *lineEdit_v1_4;
    QLabel *label_51;
    QLineEdit *lineEdit_err_4;
    QLabel *label_52;
    QLabel *label_53;
    QGroupBox *gbox_meter_5;
    QLabel *label_54;
    QLineEdit *lineEdit_sn_5;
    QLineEdit *lineEdit_e0_5;
    QLabel *label_55;
    QLineEdit *lineEdit_v0_5;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QLabel *label_60;
    QLineEdit *lineEdit_e1_5;
    QLabel *label_61;
    QLineEdit *lineEdit_v1_5;
    QLabel *label_62;
    QLineEdit *lineEdit_err_5;
    QLabel *label_63;
    QLabel *label_64;
    QGroupBox *gbox_meter_6;
    QLabel *label_65;
    QLineEdit *lineEdit_sn_6;
    QLineEdit *lineEdit_e0_6;
    QLabel *label_66;
    QLineEdit *lineEdit_v0_6;
    QLabel *label_67;
    QLabel *label_68;
    QLabel *label_69;
    QLabel *label_70;
    QLabel *label_71;
    QLineEdit *lineEdit_e1_6;
    QLabel *label_72;
    QLineEdit *lineEdit_v1_6;
    QLabel *label_73;
    QLineEdit *lineEdit_err_6;
    QLabel *label_74;
    QLabel *label_75;
    QGroupBox *gbox_meter_7;
    QLabel *label_76;
    QLineEdit *lineEdit_sn_7;
    QLineEdit *lineEdit_e0_7;
    QLabel *label_77;
    QLineEdit *lineEdit_v0_7;
    QLabel *label_78;
    QLabel *label_79;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLineEdit *lineEdit_e1_7;
    QLabel *label_83;
    QLineEdit *lineEdit_v1_7;
    QLabel *label_84;
    QLineEdit *lineEdit_err_7;
    QLabel *label_85;
    QLabel *label_86;
    QGroupBox *gbox_meter_8;
    QLabel *label_87;
    QLineEdit *lineEdit_sn_8;
    QLineEdit *lineEdit_e0_8;
    QLabel *label_88;
    QLineEdit *lineEdit_v0_8;
    QLabel *label_89;
    QLabel *label_90;
    QLabel *label_91;
    QLabel *label_92;
    QLabel *label_93;
    QLineEdit *lineEdit_e1_8;
    QLabel *label_94;
    QLineEdit *lineEdit_v1_8;
    QLabel *label_95;
    QLineEdit *lineEdit_err_8;
    QLabel *label_96;
    QLabel *label_97;
    QGroupBox *gbox_meter_9;
    QLabel *label_98;
    QLineEdit *lineEdit_sn_9;
    QLineEdit *lineEdit_e0_9;
    QLabel *label_99;
    QLineEdit *lineEdit_v0_9;
    QLabel *label_100;
    QLabel *label_101;
    QLabel *label_102;
    QLabel *label_103;
    QLabel *label_104;
    QLineEdit *lineEdit_e1_9;
    QLabel *label_105;
    QLineEdit *lineEdit_v1_9;
    QLabel *label_106;
    QLineEdit *lineEdit_err_9;
    QLabel *label_107;
    QLabel *label_108;
    QGroupBox *gbox_meter_10;
    QLabel *label_109;
    QLineEdit *lineEdit_sn_10;
    QLineEdit *lineEdit_e0_10;
    QLabel *label_110;
    QLineEdit *lineEdit_v0_10;
    QLabel *label_111;
    QLabel *label_112;
    QLabel *label_113;
    QLabel *label_114;
    QLabel *label_115;
    QLineEdit *lineEdit_e1_10;
    QLabel *label_116;
    QLineEdit *lineEdit_v1_10;
    QLabel *label_117;
    QLineEdit *lineEdit_err_10;
    QLabel *label_118;
    QLabel *label_119;
    QGroupBox *gbox_meter_11;
    QLabel *label_120;
    QLineEdit *lineEdit_sn_11;
    QLineEdit *lineEdit_e0_11;
    QLabel *label_121;
    QLineEdit *lineEdit_v0_11;
    QLabel *label_122;
    QLabel *label_123;
    QLabel *label_124;
    QLabel *label_125;
    QLabel *label_126;
    QLineEdit *lineEdit_e1_11;
    QLabel *label_127;
    QLineEdit *lineEdit_v1_11;
    QLabel *label_128;
    QLineEdit *lineEdit_err_11;
    QLabel *label_129;
    QLabel *label_130;
    QGroupBox *gbox_meter_12;
    QLabel *label_131;
    QLineEdit *lineEdit_sn_12;
    QLineEdit *lineEdit_e0_12;
    QLabel *label_132;
    QLineEdit *lineEdit_v0_12;
    QLabel *label_133;
    QLabel *label_134;
    QLabel *label_135;
    QLabel *label_136;
    QLabel *label_137;
    QLineEdit *lineEdit_e1_12;
    QLabel *label_138;
    QLineEdit *lineEdit_v1_12;
    QLabel *label_139;
    QLineEdit *lineEdit_err_12;
    QLabel *label_140;
    QLabel *label_141;

    void setupUi(QWidget *CmbVerifyClass)
    {
        if (CmbVerifyClass->objectName().isEmpty())
            CmbVerifyClass->setObjectName(QString::fromUtf8("CmbVerifyClass"));
        CmbVerifyClass->resize(914, 609);
        label_208 = new QLabel(CmbVerifyClass);
        label_208->setObjectName(QString::fromUtf8("label_208"));
        label_208->setGeometry(QRect(30, 550, 271, 41));
        btnPara = new QPushButton(CmbVerifyClass);
        btnPara->setObjectName(QString::fromUtf8("btnPara"));
        btnPara->setGeometry(QRect(530, 550, 91, 41));
        QIcon icon;
        icon.addFile(QString::fromUtf8("../source/gui/images/calculatorresult.png"), QSize(), QIcon::Normal, QIcon::Off);
        btnPara->setIcon(icon);
        btnExit = new QPushButton(CmbVerifyClass);
        btnExit->setObjectName(QString::fromUtf8("btnExit"));
        btnExit->setGeometry(QRect(820, 550, 75, 41));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("../../exit.png"), QSize(), QIcon::Normal, QIcon::Off);
        btnExit->setIcon(icon1);
        pushButton_5 = new QPushButton(CmbVerifyClass);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(640, 550, 75, 41));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8("../source/gui/images/tempercompare.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_5->setIcon(icon2);
        pushButton_6 = new QPushButton(CmbVerifyClass);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(730, 550, 75, 41));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8("../source/gui/images/save.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_6->setIcon(icon3);
        frame = new QFrame(CmbVerifyClass);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(10, 10, 891, 80));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        label = new QLabel(frame);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 20, 61, 31));
        groupBox = new QGroupBox(frame);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(80, 10, 111, 51));
        rbtn_pos_in = new QRadioButton(groupBox);
        rbtn_pos_in->setObjectName(QString::fromUtf8("rbtn_pos_in"));
        rbtn_pos_in->setGeometry(QRect(10, 20, 41, 16));
        rbtn_pos_out = new QRadioButton(groupBox);
        rbtn_pos_out->setObjectName(QString::fromUtf8("rbtn_pos_out"));
        rbtn_pos_out->setGeometry(QRect(60, 20, 41, 16));
        groupBox_2 = new QGroupBox(frame);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(210, 10, 111, 51));
        rbtn_unit_kwh = new QRadioButton(groupBox_2);
        rbtn_unit_kwh->setObjectName(QString::fromUtf8("rbtn_unit_kwh"));
        rbtn_unit_kwh->setGeometry(QRect(10, 20, 41, 16));
        rbtn_unit_mj = new QRadioButton(groupBox_2);
        rbtn_unit_mj->setObjectName(QString::fromUtf8("rbtn_unit_mj"));
        rbtn_unit_mj->setGeometry(QRect(60, 20, 41, 16));
        groupBox_3 = new QGroupBox(frame);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(340, 10, 111, 51));
        label_2 = new QLabel(groupBox_3);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 20, 31, 16));
        label_3 = new QLabel(groupBox_3);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(80, 20, 16, 16));
        lineEdit_min_theta = new QLineEdit(groupBox_3);
        lineEdit_min_theta->setObjectName(QString::fromUtf8("lineEdit_min_theta"));
        lineEdit_min_theta->setGeometry(QRect(50, 20, 21, 20));
        groupBox_4 = new QGroupBox(frame);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(460, 10, 411, 51));
        label_4 = new QLabel(groupBox_4);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(110, 20, 31, 16));
        label_5 = new QLabel(groupBox_4);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(180, 20, 16, 16));
        lineEdit_std_in_r = new QLineEdit(groupBox_4);
        lineEdit_std_in_r->setObjectName(QString::fromUtf8("lineEdit_std_in_r"));
        lineEdit_std_in_r->setGeometry(QRect(150, 20, 21, 20));
        btn_collection = new QPushButton(groupBox_4);
        btn_collection->setObjectName(QString::fromUtf8("btn_collection"));
        btn_collection->setGeometry(QRect(10, 20, 51, 23));
        btn_stop = new QPushButton(groupBox_4);
        btn_stop->setObjectName(QString::fromUtf8("btn_stop"));
        btn_stop->setGeometry(QRect(70, 20, 31, 23));
        label_6 = new QLabel(groupBox_4);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(230, 20, 16, 16));
        lineEdit_std_in_t = new QLineEdit(groupBox_4);
        lineEdit_std_in_t->setObjectName(QString::fromUtf8("lineEdit_std_in_t"));
        lineEdit_std_in_t->setGeometry(QRect(200, 20, 21, 20));
        label_7 = new QLabel(groupBox_4);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(380, 20, 16, 16));
        lineEdit_std_out_t = new QLineEdit(groupBox_4);
        lineEdit_std_out_t->setObjectName(QString::fromUtf8("lineEdit_std_out_t"));
        lineEdit_std_out_t->setGeometry(QRect(350, 20, 21, 20));
        label_8 = new QLabel(groupBox_4);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(320, 20, 16, 16));
        lineEdit_std_out_r = new QLineEdit(groupBox_4);
        lineEdit_std_out_r->setObjectName(QString::fromUtf8("lineEdit_std_out_r"));
        lineEdit_std_out_r->setGeometry(QRect(290, 20, 21, 20));
        label_9 = new QLabel(groupBox_4);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(250, 20, 31, 16));
        gbox_meter_1 = new QGroupBox(CmbVerifyClass);
        gbox_meter_1->setObjectName(QString::fromUtf8("gbox_meter_1"));
        gbox_meter_1->setGeometry(QRect(10, 100, 141, 221));
        label_10 = new QLabel(gbox_meter_1);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_1 = new QLineEdit(gbox_meter_1);
        lineEdit_sn_1->setObjectName(QString::fromUtf8("lineEdit_sn_1"));
        lineEdit_sn_1->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_1 = new QLineEdit(gbox_meter_1);
        lineEdit_e0_1->setObjectName(QString::fromUtf8("lineEdit_e0_1"));
        lineEdit_e0_1->setGeometry(QRect(40, 60, 71, 20));
        label_11 = new QLabel(gbox_meter_1);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_1 = new QLineEdit(gbox_meter_1);
        lineEdit_v0_1->setObjectName(QString::fromUtf8("lineEdit_v0_1"));
        lineEdit_v0_1->setGeometry(QRect(40, 90, 71, 20));
        label_12 = new QLabel(gbox_meter_1);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 90, 21, 16));
        label_13 = new QLabel(gbox_meter_1);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 120, 21, 16));
        label_16 = new QLabel(gbox_meter_1);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(120, 60, 21, 16));
        label_17 = new QLabel(gbox_meter_1);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(120, 90, 21, 16));
        label_18 = new QLabel(gbox_meter_1);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_1 = new QLineEdit(gbox_meter_1);
        lineEdit_e1_1->setObjectName(QString::fromUtf8("lineEdit_e1_1"));
        lineEdit_e1_1->setGeometry(QRect(40, 120, 71, 20));
        label_19 = new QLabel(gbox_meter_1);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_1 = new QLineEdit(gbox_meter_1);
        lineEdit_v1_1->setObjectName(QString::fromUtf8("lineEdit_v1_1"));
        lineEdit_v1_1->setGeometry(QRect(40, 150, 71, 20));
        label_14 = new QLabel(gbox_meter_1);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_1 = new QLineEdit(gbox_meter_1);
        lineEdit_err_1->setObjectName(QString::fromUtf8("lineEdit_err_1"));
        lineEdit_err_1->setEnabled(false);
        lineEdit_err_1->setGeometry(QRect(40, 180, 41, 20));
        label_15 = new QLabel(gbox_meter_1);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(10, 180, 21, 16));
        label_20 = new QLabel(gbox_meter_1);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_2 = new QGroupBox(CmbVerifyClass);
        gbox_meter_2->setObjectName(QString::fromUtf8("gbox_meter_2"));
        gbox_meter_2->setGeometry(QRect(160, 100, 141, 221));
        label_21 = new QLabel(gbox_meter_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_2 = new QLineEdit(gbox_meter_2);
        lineEdit_sn_2->setObjectName(QString::fromUtf8("lineEdit_sn_2"));
        lineEdit_sn_2->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_2 = new QLineEdit(gbox_meter_2);
        lineEdit_e0_2->setObjectName(QString::fromUtf8("lineEdit_e0_2"));
        lineEdit_e0_2->setGeometry(QRect(40, 60, 71, 20));
        label_22 = new QLabel(gbox_meter_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_2 = new QLineEdit(gbox_meter_2);
        lineEdit_v0_2->setObjectName(QString::fromUtf8("lineEdit_v0_2"));
        lineEdit_v0_2->setGeometry(QRect(40, 90, 71, 20));
        label_23 = new QLabel(gbox_meter_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(10, 90, 21, 16));
        label_24 = new QLabel(gbox_meter_2);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(10, 120, 21, 16));
        label_25 = new QLabel(gbox_meter_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(120, 60, 21, 16));
        label_26 = new QLabel(gbox_meter_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(120, 90, 21, 16));
        label_27 = new QLabel(gbox_meter_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_2 = new QLineEdit(gbox_meter_2);
        lineEdit_e1_2->setObjectName(QString::fromUtf8("lineEdit_e1_2"));
        lineEdit_e1_2->setGeometry(QRect(40, 120, 71, 20));
        label_28 = new QLabel(gbox_meter_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_2 = new QLineEdit(gbox_meter_2);
        lineEdit_v1_2->setObjectName(QString::fromUtf8("lineEdit_v1_2"));
        lineEdit_v1_2->setGeometry(QRect(40, 150, 71, 20));
        label_29 = new QLabel(gbox_meter_2);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_2 = new QLineEdit(gbox_meter_2);
        lineEdit_err_2->setObjectName(QString::fromUtf8("lineEdit_err_2"));
        lineEdit_err_2->setEnabled(false);
        lineEdit_err_2->setGeometry(QRect(40, 180, 41, 20));
        label_30 = new QLabel(gbox_meter_2);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(10, 180, 21, 16));
        label_31 = new QLabel(gbox_meter_2);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_3 = new QGroupBox(CmbVerifyClass);
        gbox_meter_3->setObjectName(QString::fromUtf8("gbox_meter_3"));
        gbox_meter_3->setGeometry(QRect(310, 100, 141, 221));
        label_32 = new QLabel(gbox_meter_3);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_3 = new QLineEdit(gbox_meter_3);
        lineEdit_sn_3->setObjectName(QString::fromUtf8("lineEdit_sn_3"));
        lineEdit_sn_3->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_3 = new QLineEdit(gbox_meter_3);
        lineEdit_e0_3->setObjectName(QString::fromUtf8("lineEdit_e0_3"));
        lineEdit_e0_3->setGeometry(QRect(40, 60, 71, 20));
        label_33 = new QLabel(gbox_meter_3);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_3 = new QLineEdit(gbox_meter_3);
        lineEdit_v0_3->setObjectName(QString::fromUtf8("lineEdit_v0_3"));
        lineEdit_v0_3->setGeometry(QRect(40, 90, 71, 20));
        label_34 = new QLabel(gbox_meter_3);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(10, 90, 21, 16));
        label_35 = new QLabel(gbox_meter_3);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(10, 120, 21, 16));
        label_36 = new QLabel(gbox_meter_3);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(120, 60, 21, 16));
        label_37 = new QLabel(gbox_meter_3);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(120, 90, 21, 16));
        label_38 = new QLabel(gbox_meter_3);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_3 = new QLineEdit(gbox_meter_3);
        lineEdit_e1_3->setObjectName(QString::fromUtf8("lineEdit_e1_3"));
        lineEdit_e1_3->setGeometry(QRect(40, 120, 71, 20));
        label_39 = new QLabel(gbox_meter_3);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_3 = new QLineEdit(gbox_meter_3);
        lineEdit_v1_3->setObjectName(QString::fromUtf8("lineEdit_v1_3"));
        lineEdit_v1_3->setGeometry(QRect(40, 150, 71, 20));
        label_40 = new QLabel(gbox_meter_3);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_3 = new QLineEdit(gbox_meter_3);
        lineEdit_err_3->setObjectName(QString::fromUtf8("lineEdit_err_3"));
        lineEdit_err_3->setEnabled(false);
        lineEdit_err_3->setGeometry(QRect(40, 180, 41, 20));
        label_41 = new QLabel(gbox_meter_3);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(10, 180, 21, 16));
        label_42 = new QLabel(gbox_meter_3);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_4 = new QGroupBox(CmbVerifyClass);
        gbox_meter_4->setObjectName(QString::fromUtf8("gbox_meter_4"));
        gbox_meter_4->setGeometry(QRect(460, 100, 141, 221));
        label_43 = new QLabel(gbox_meter_4);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_4 = new QLineEdit(gbox_meter_4);
        lineEdit_sn_4->setObjectName(QString::fromUtf8("lineEdit_sn_4"));
        lineEdit_sn_4->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_4 = new QLineEdit(gbox_meter_4);
        lineEdit_e0_4->setObjectName(QString::fromUtf8("lineEdit_e0_4"));
        lineEdit_e0_4->setGeometry(QRect(40, 60, 71, 20));
        label_44 = new QLabel(gbox_meter_4);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_4 = new QLineEdit(gbox_meter_4);
        lineEdit_v0_4->setObjectName(QString::fromUtf8("lineEdit_v0_4"));
        lineEdit_v0_4->setGeometry(QRect(40, 90, 71, 20));
        label_45 = new QLabel(gbox_meter_4);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(10, 90, 21, 16));
        label_46 = new QLabel(gbox_meter_4);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(10, 120, 21, 16));
        label_47 = new QLabel(gbox_meter_4);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(120, 60, 21, 16));
        label_48 = new QLabel(gbox_meter_4);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(120, 90, 21, 16));
        label_49 = new QLabel(gbox_meter_4);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_4 = new QLineEdit(gbox_meter_4);
        lineEdit_e1_4->setObjectName(QString::fromUtf8("lineEdit_e1_4"));
        lineEdit_e1_4->setGeometry(QRect(40, 120, 71, 20));
        label_50 = new QLabel(gbox_meter_4);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_4 = new QLineEdit(gbox_meter_4);
        lineEdit_v1_4->setObjectName(QString::fromUtf8("lineEdit_v1_4"));
        lineEdit_v1_4->setGeometry(QRect(40, 150, 71, 20));
        label_51 = new QLabel(gbox_meter_4);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_4 = new QLineEdit(gbox_meter_4);
        lineEdit_err_4->setObjectName(QString::fromUtf8("lineEdit_err_4"));
        lineEdit_err_4->setEnabled(false);
        lineEdit_err_4->setGeometry(QRect(40, 180, 41, 20));
        label_52 = new QLabel(gbox_meter_4);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(10, 180, 21, 16));
        label_53 = new QLabel(gbox_meter_4);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_5 = new QGroupBox(CmbVerifyClass);
        gbox_meter_5->setObjectName(QString::fromUtf8("gbox_meter_5"));
        gbox_meter_5->setGeometry(QRect(610, 100, 141, 221));
        label_54 = new QLabel(gbox_meter_5);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_5 = new QLineEdit(gbox_meter_5);
        lineEdit_sn_5->setObjectName(QString::fromUtf8("lineEdit_sn_5"));
        lineEdit_sn_5->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_5 = new QLineEdit(gbox_meter_5);
        lineEdit_e0_5->setObjectName(QString::fromUtf8("lineEdit_e0_5"));
        lineEdit_e0_5->setGeometry(QRect(40, 60, 71, 20));
        label_55 = new QLabel(gbox_meter_5);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_5 = new QLineEdit(gbox_meter_5);
        lineEdit_v0_5->setObjectName(QString::fromUtf8("lineEdit_v0_5"));
        lineEdit_v0_5->setGeometry(QRect(40, 90, 71, 20));
        label_56 = new QLabel(gbox_meter_5);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(10, 90, 21, 16));
        label_57 = new QLabel(gbox_meter_5);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(10, 120, 21, 16));
        label_58 = new QLabel(gbox_meter_5);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(120, 60, 21, 16));
        label_59 = new QLabel(gbox_meter_5);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(120, 90, 21, 16));
        label_60 = new QLabel(gbox_meter_5);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_5 = new QLineEdit(gbox_meter_5);
        lineEdit_e1_5->setObjectName(QString::fromUtf8("lineEdit_e1_5"));
        lineEdit_e1_5->setGeometry(QRect(40, 120, 71, 20));
        label_61 = new QLabel(gbox_meter_5);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_5 = new QLineEdit(gbox_meter_5);
        lineEdit_v1_5->setObjectName(QString::fromUtf8("lineEdit_v1_5"));
        lineEdit_v1_5->setGeometry(QRect(40, 150, 71, 20));
        label_62 = new QLabel(gbox_meter_5);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_5 = new QLineEdit(gbox_meter_5);
        lineEdit_err_5->setObjectName(QString::fromUtf8("lineEdit_err_5"));
        lineEdit_err_5->setEnabled(false);
        lineEdit_err_5->setGeometry(QRect(40, 180, 41, 20));
        label_63 = new QLabel(gbox_meter_5);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(10, 180, 21, 16));
        label_64 = new QLabel(gbox_meter_5);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_6 = new QGroupBox(CmbVerifyClass);
        gbox_meter_6->setObjectName(QString::fromUtf8("gbox_meter_6"));
        gbox_meter_6->setGeometry(QRect(760, 100, 141, 221));
        label_65 = new QLabel(gbox_meter_6);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_6 = new QLineEdit(gbox_meter_6);
        lineEdit_sn_6->setObjectName(QString::fromUtf8("lineEdit_sn_6"));
        lineEdit_sn_6->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_6 = new QLineEdit(gbox_meter_6);
        lineEdit_e0_6->setObjectName(QString::fromUtf8("lineEdit_e0_6"));
        lineEdit_e0_6->setGeometry(QRect(40, 60, 71, 20));
        label_66 = new QLabel(gbox_meter_6);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_6 = new QLineEdit(gbox_meter_6);
        lineEdit_v0_6->setObjectName(QString::fromUtf8("lineEdit_v0_6"));
        lineEdit_v0_6->setGeometry(QRect(40, 90, 71, 20));
        label_67 = new QLabel(gbox_meter_6);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(10, 90, 21, 16));
        label_68 = new QLabel(gbox_meter_6);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(10, 120, 21, 16));
        label_69 = new QLabel(gbox_meter_6);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(120, 60, 21, 16));
        label_70 = new QLabel(gbox_meter_6);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(120, 90, 21, 16));
        label_71 = new QLabel(gbox_meter_6);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_6 = new QLineEdit(gbox_meter_6);
        lineEdit_e1_6->setObjectName(QString::fromUtf8("lineEdit_e1_6"));
        lineEdit_e1_6->setGeometry(QRect(40, 120, 71, 20));
        label_72 = new QLabel(gbox_meter_6);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_6 = new QLineEdit(gbox_meter_6);
        lineEdit_v1_6->setObjectName(QString::fromUtf8("lineEdit_v1_6"));
        lineEdit_v1_6->setGeometry(QRect(40, 150, 71, 20));
        label_73 = new QLabel(gbox_meter_6);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_6 = new QLineEdit(gbox_meter_6);
        lineEdit_err_6->setObjectName(QString::fromUtf8("lineEdit_err_6"));
        lineEdit_err_6->setEnabled(false);
        lineEdit_err_6->setGeometry(QRect(40, 180, 41, 20));
        label_74 = new QLabel(gbox_meter_6);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(10, 180, 21, 16));
        label_75 = new QLabel(gbox_meter_6);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_7 = new QGroupBox(CmbVerifyClass);
        gbox_meter_7->setObjectName(QString::fromUtf8("gbox_meter_7"));
        gbox_meter_7->setGeometry(QRect(10, 320, 141, 221));
        label_76 = new QLabel(gbox_meter_7);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_7 = new QLineEdit(gbox_meter_7);
        lineEdit_sn_7->setObjectName(QString::fromUtf8("lineEdit_sn_7"));
        lineEdit_sn_7->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_7 = new QLineEdit(gbox_meter_7);
        lineEdit_e0_7->setObjectName(QString::fromUtf8("lineEdit_e0_7"));
        lineEdit_e0_7->setGeometry(QRect(40, 60, 71, 20));
        label_77 = new QLabel(gbox_meter_7);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_7 = new QLineEdit(gbox_meter_7);
        lineEdit_v0_7->setObjectName(QString::fromUtf8("lineEdit_v0_7"));
        lineEdit_v0_7->setGeometry(QRect(40, 90, 71, 20));
        label_78 = new QLabel(gbox_meter_7);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(10, 90, 21, 16));
        label_79 = new QLabel(gbox_meter_7);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(10, 120, 21, 16));
        label_80 = new QLabel(gbox_meter_7);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(120, 60, 21, 16));
        label_81 = new QLabel(gbox_meter_7);
        label_81->setObjectName(QString::fromUtf8("label_81"));
        label_81->setGeometry(QRect(120, 90, 21, 16));
        label_82 = new QLabel(gbox_meter_7);
        label_82->setObjectName(QString::fromUtf8("label_82"));
        label_82->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_7 = new QLineEdit(gbox_meter_7);
        lineEdit_e1_7->setObjectName(QString::fromUtf8("lineEdit_e1_7"));
        lineEdit_e1_7->setGeometry(QRect(40, 120, 71, 20));
        label_83 = new QLabel(gbox_meter_7);
        label_83->setObjectName(QString::fromUtf8("label_83"));
        label_83->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_7 = new QLineEdit(gbox_meter_7);
        lineEdit_v1_7->setObjectName(QString::fromUtf8("lineEdit_v1_7"));
        lineEdit_v1_7->setGeometry(QRect(40, 150, 71, 20));
        label_84 = new QLabel(gbox_meter_7);
        label_84->setObjectName(QString::fromUtf8("label_84"));
        label_84->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_7 = new QLineEdit(gbox_meter_7);
        lineEdit_err_7->setObjectName(QString::fromUtf8("lineEdit_err_7"));
        lineEdit_err_7->setEnabled(false);
        lineEdit_err_7->setGeometry(QRect(40, 180, 41, 20));
        label_85 = new QLabel(gbox_meter_7);
        label_85->setObjectName(QString::fromUtf8("label_85"));
        label_85->setGeometry(QRect(10, 180, 21, 16));
        label_86 = new QLabel(gbox_meter_7);
        label_86->setObjectName(QString::fromUtf8("label_86"));
        label_86->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_8 = new QGroupBox(CmbVerifyClass);
        gbox_meter_8->setObjectName(QString::fromUtf8("gbox_meter_8"));
        gbox_meter_8->setGeometry(QRect(160, 320, 141, 221));
        label_87 = new QLabel(gbox_meter_8);
        label_87->setObjectName(QString::fromUtf8("label_87"));
        label_87->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_8 = new QLineEdit(gbox_meter_8);
        lineEdit_sn_8->setObjectName(QString::fromUtf8("lineEdit_sn_8"));
        lineEdit_sn_8->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_8 = new QLineEdit(gbox_meter_8);
        lineEdit_e0_8->setObjectName(QString::fromUtf8("lineEdit_e0_8"));
        lineEdit_e0_8->setGeometry(QRect(40, 60, 71, 20));
        label_88 = new QLabel(gbox_meter_8);
        label_88->setObjectName(QString::fromUtf8("label_88"));
        label_88->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_8 = new QLineEdit(gbox_meter_8);
        lineEdit_v0_8->setObjectName(QString::fromUtf8("lineEdit_v0_8"));
        lineEdit_v0_8->setGeometry(QRect(40, 90, 71, 20));
        label_89 = new QLabel(gbox_meter_8);
        label_89->setObjectName(QString::fromUtf8("label_89"));
        label_89->setGeometry(QRect(10, 90, 21, 16));
        label_90 = new QLabel(gbox_meter_8);
        label_90->setObjectName(QString::fromUtf8("label_90"));
        label_90->setGeometry(QRect(10, 120, 21, 16));
        label_91 = new QLabel(gbox_meter_8);
        label_91->setObjectName(QString::fromUtf8("label_91"));
        label_91->setGeometry(QRect(120, 60, 21, 16));
        label_92 = new QLabel(gbox_meter_8);
        label_92->setObjectName(QString::fromUtf8("label_92"));
        label_92->setGeometry(QRect(120, 90, 21, 16));
        label_93 = new QLabel(gbox_meter_8);
        label_93->setObjectName(QString::fromUtf8("label_93"));
        label_93->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_8 = new QLineEdit(gbox_meter_8);
        lineEdit_e1_8->setObjectName(QString::fromUtf8("lineEdit_e1_8"));
        lineEdit_e1_8->setGeometry(QRect(40, 120, 71, 20));
        label_94 = new QLabel(gbox_meter_8);
        label_94->setObjectName(QString::fromUtf8("label_94"));
        label_94->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_8 = new QLineEdit(gbox_meter_8);
        lineEdit_v1_8->setObjectName(QString::fromUtf8("lineEdit_v1_8"));
        lineEdit_v1_8->setGeometry(QRect(40, 150, 71, 20));
        label_95 = new QLabel(gbox_meter_8);
        label_95->setObjectName(QString::fromUtf8("label_95"));
        label_95->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_8 = new QLineEdit(gbox_meter_8);
        lineEdit_err_8->setObjectName(QString::fromUtf8("lineEdit_err_8"));
        lineEdit_err_8->setEnabled(false);
        lineEdit_err_8->setGeometry(QRect(40, 180, 41, 20));
        label_96 = new QLabel(gbox_meter_8);
        label_96->setObjectName(QString::fromUtf8("label_96"));
        label_96->setGeometry(QRect(10, 180, 21, 16));
        label_97 = new QLabel(gbox_meter_8);
        label_97->setObjectName(QString::fromUtf8("label_97"));
        label_97->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_9 = new QGroupBox(CmbVerifyClass);
        gbox_meter_9->setObjectName(QString::fromUtf8("gbox_meter_9"));
        gbox_meter_9->setGeometry(QRect(310, 320, 141, 221));
        label_98 = new QLabel(gbox_meter_9);
        label_98->setObjectName(QString::fromUtf8("label_98"));
        label_98->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_9 = new QLineEdit(gbox_meter_9);
        lineEdit_sn_9->setObjectName(QString::fromUtf8("lineEdit_sn_9"));
        lineEdit_sn_9->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_9 = new QLineEdit(gbox_meter_9);
        lineEdit_e0_9->setObjectName(QString::fromUtf8("lineEdit_e0_9"));
        lineEdit_e0_9->setGeometry(QRect(40, 60, 71, 20));
        label_99 = new QLabel(gbox_meter_9);
        label_99->setObjectName(QString::fromUtf8("label_99"));
        label_99->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_9 = new QLineEdit(gbox_meter_9);
        lineEdit_v0_9->setObjectName(QString::fromUtf8("lineEdit_v0_9"));
        lineEdit_v0_9->setGeometry(QRect(40, 90, 71, 20));
        label_100 = new QLabel(gbox_meter_9);
        label_100->setObjectName(QString::fromUtf8("label_100"));
        label_100->setGeometry(QRect(10, 90, 21, 16));
        label_101 = new QLabel(gbox_meter_9);
        label_101->setObjectName(QString::fromUtf8("label_101"));
        label_101->setGeometry(QRect(10, 120, 21, 16));
        label_102 = new QLabel(gbox_meter_9);
        label_102->setObjectName(QString::fromUtf8("label_102"));
        label_102->setGeometry(QRect(120, 60, 21, 16));
        label_103 = new QLabel(gbox_meter_9);
        label_103->setObjectName(QString::fromUtf8("label_103"));
        label_103->setGeometry(QRect(120, 90, 21, 16));
        label_104 = new QLabel(gbox_meter_9);
        label_104->setObjectName(QString::fromUtf8("label_104"));
        label_104->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_9 = new QLineEdit(gbox_meter_9);
        lineEdit_e1_9->setObjectName(QString::fromUtf8("lineEdit_e1_9"));
        lineEdit_e1_9->setGeometry(QRect(40, 120, 71, 20));
        label_105 = new QLabel(gbox_meter_9);
        label_105->setObjectName(QString::fromUtf8("label_105"));
        label_105->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_9 = new QLineEdit(gbox_meter_9);
        lineEdit_v1_9->setObjectName(QString::fromUtf8("lineEdit_v1_9"));
        lineEdit_v1_9->setGeometry(QRect(40, 150, 71, 20));
        label_106 = new QLabel(gbox_meter_9);
        label_106->setObjectName(QString::fromUtf8("label_106"));
        label_106->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_9 = new QLineEdit(gbox_meter_9);
        lineEdit_err_9->setObjectName(QString::fromUtf8("lineEdit_err_9"));
        lineEdit_err_9->setEnabled(false);
        lineEdit_err_9->setGeometry(QRect(40, 180, 41, 20));
        label_107 = new QLabel(gbox_meter_9);
        label_107->setObjectName(QString::fromUtf8("label_107"));
        label_107->setGeometry(QRect(10, 180, 21, 16));
        label_108 = new QLabel(gbox_meter_9);
        label_108->setObjectName(QString::fromUtf8("label_108"));
        label_108->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_10 = new QGroupBox(CmbVerifyClass);
        gbox_meter_10->setObjectName(QString::fromUtf8("gbox_meter_10"));
        gbox_meter_10->setGeometry(QRect(460, 320, 141, 221));
        label_109 = new QLabel(gbox_meter_10);
        label_109->setObjectName(QString::fromUtf8("label_109"));
        label_109->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_10 = new QLineEdit(gbox_meter_10);
        lineEdit_sn_10->setObjectName(QString::fromUtf8("lineEdit_sn_10"));
        lineEdit_sn_10->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_10 = new QLineEdit(gbox_meter_10);
        lineEdit_e0_10->setObjectName(QString::fromUtf8("lineEdit_e0_10"));
        lineEdit_e0_10->setGeometry(QRect(40, 60, 71, 20));
        label_110 = new QLabel(gbox_meter_10);
        label_110->setObjectName(QString::fromUtf8("label_110"));
        label_110->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_10 = new QLineEdit(gbox_meter_10);
        lineEdit_v0_10->setObjectName(QString::fromUtf8("lineEdit_v0_10"));
        lineEdit_v0_10->setGeometry(QRect(40, 90, 71, 20));
        label_111 = new QLabel(gbox_meter_10);
        label_111->setObjectName(QString::fromUtf8("label_111"));
        label_111->setGeometry(QRect(10, 90, 21, 16));
        label_112 = new QLabel(gbox_meter_10);
        label_112->setObjectName(QString::fromUtf8("label_112"));
        label_112->setGeometry(QRect(10, 120, 21, 16));
        label_113 = new QLabel(gbox_meter_10);
        label_113->setObjectName(QString::fromUtf8("label_113"));
        label_113->setGeometry(QRect(120, 60, 21, 16));
        label_114 = new QLabel(gbox_meter_10);
        label_114->setObjectName(QString::fromUtf8("label_114"));
        label_114->setGeometry(QRect(120, 90, 21, 16));
        label_115 = new QLabel(gbox_meter_10);
        label_115->setObjectName(QString::fromUtf8("label_115"));
        label_115->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_10 = new QLineEdit(gbox_meter_10);
        lineEdit_e1_10->setObjectName(QString::fromUtf8("lineEdit_e1_10"));
        lineEdit_e1_10->setGeometry(QRect(40, 120, 71, 20));
        label_116 = new QLabel(gbox_meter_10);
        label_116->setObjectName(QString::fromUtf8("label_116"));
        label_116->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_10 = new QLineEdit(gbox_meter_10);
        lineEdit_v1_10->setObjectName(QString::fromUtf8("lineEdit_v1_10"));
        lineEdit_v1_10->setGeometry(QRect(40, 150, 71, 20));
        label_117 = new QLabel(gbox_meter_10);
        label_117->setObjectName(QString::fromUtf8("label_117"));
        label_117->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_10 = new QLineEdit(gbox_meter_10);
        lineEdit_err_10->setObjectName(QString::fromUtf8("lineEdit_err_10"));
        lineEdit_err_10->setEnabled(false);
        lineEdit_err_10->setGeometry(QRect(40, 180, 41, 20));
        label_118 = new QLabel(gbox_meter_10);
        label_118->setObjectName(QString::fromUtf8("label_118"));
        label_118->setGeometry(QRect(10, 180, 21, 16));
        label_119 = new QLabel(gbox_meter_10);
        label_119->setObjectName(QString::fromUtf8("label_119"));
        label_119->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_11 = new QGroupBox(CmbVerifyClass);
        gbox_meter_11->setObjectName(QString::fromUtf8("gbox_meter_11"));
        gbox_meter_11->setGeometry(QRect(610, 320, 141, 221));
        label_120 = new QLabel(gbox_meter_11);
        label_120->setObjectName(QString::fromUtf8("label_120"));
        label_120->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_11 = new QLineEdit(gbox_meter_11);
        lineEdit_sn_11->setObjectName(QString::fromUtf8("lineEdit_sn_11"));
        lineEdit_sn_11->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_11 = new QLineEdit(gbox_meter_11);
        lineEdit_e0_11->setObjectName(QString::fromUtf8("lineEdit_e0_11"));
        lineEdit_e0_11->setGeometry(QRect(40, 60, 71, 20));
        label_121 = new QLabel(gbox_meter_11);
        label_121->setObjectName(QString::fromUtf8("label_121"));
        label_121->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_11 = new QLineEdit(gbox_meter_11);
        lineEdit_v0_11->setObjectName(QString::fromUtf8("lineEdit_v0_11"));
        lineEdit_v0_11->setGeometry(QRect(40, 90, 71, 20));
        label_122 = new QLabel(gbox_meter_11);
        label_122->setObjectName(QString::fromUtf8("label_122"));
        label_122->setGeometry(QRect(10, 90, 21, 16));
        label_123 = new QLabel(gbox_meter_11);
        label_123->setObjectName(QString::fromUtf8("label_123"));
        label_123->setGeometry(QRect(10, 120, 21, 16));
        label_124 = new QLabel(gbox_meter_11);
        label_124->setObjectName(QString::fromUtf8("label_124"));
        label_124->setGeometry(QRect(120, 60, 21, 16));
        label_125 = new QLabel(gbox_meter_11);
        label_125->setObjectName(QString::fromUtf8("label_125"));
        label_125->setGeometry(QRect(120, 90, 21, 16));
        label_126 = new QLabel(gbox_meter_11);
        label_126->setObjectName(QString::fromUtf8("label_126"));
        label_126->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_11 = new QLineEdit(gbox_meter_11);
        lineEdit_e1_11->setObjectName(QString::fromUtf8("lineEdit_e1_11"));
        lineEdit_e1_11->setGeometry(QRect(40, 120, 71, 20));
        label_127 = new QLabel(gbox_meter_11);
        label_127->setObjectName(QString::fromUtf8("label_127"));
        label_127->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_11 = new QLineEdit(gbox_meter_11);
        lineEdit_v1_11->setObjectName(QString::fromUtf8("lineEdit_v1_11"));
        lineEdit_v1_11->setGeometry(QRect(40, 150, 71, 20));
        label_128 = new QLabel(gbox_meter_11);
        label_128->setObjectName(QString::fromUtf8("label_128"));
        label_128->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_11 = new QLineEdit(gbox_meter_11);
        lineEdit_err_11->setObjectName(QString::fromUtf8("lineEdit_err_11"));
        lineEdit_err_11->setEnabled(false);
        lineEdit_err_11->setGeometry(QRect(40, 180, 41, 20));
        label_129 = new QLabel(gbox_meter_11);
        label_129->setObjectName(QString::fromUtf8("label_129"));
        label_129->setGeometry(QRect(10, 180, 21, 16));
        label_130 = new QLabel(gbox_meter_11);
        label_130->setObjectName(QString::fromUtf8("label_130"));
        label_130->setGeometry(QRect(100, 180, 21, 16));
        gbox_meter_12 = new QGroupBox(CmbVerifyClass);
        gbox_meter_12->setObjectName(QString::fromUtf8("gbox_meter_12"));
        gbox_meter_12->setGeometry(QRect(760, 320, 141, 221));
        label_131 = new QLabel(gbox_meter_12);
        label_131->setObjectName(QString::fromUtf8("label_131"));
        label_131->setGeometry(QRect(10, 30, 31, 16));
        lineEdit_sn_12 = new QLineEdit(gbox_meter_12);
        lineEdit_sn_12->setObjectName(QString::fromUtf8("lineEdit_sn_12"));
        lineEdit_sn_12->setGeometry(QRect(40, 30, 91, 20));
        lineEdit_e0_12 = new QLineEdit(gbox_meter_12);
        lineEdit_e0_12->setObjectName(QString::fromUtf8("lineEdit_e0_12"));
        lineEdit_e0_12->setGeometry(QRect(40, 60, 71, 20));
        label_132 = new QLabel(gbox_meter_12);
        label_132->setObjectName(QString::fromUtf8("label_132"));
        label_132->setGeometry(QRect(10, 60, 21, 16));
        lineEdit_v0_12 = new QLineEdit(gbox_meter_12);
        lineEdit_v0_12->setObjectName(QString::fromUtf8("lineEdit_v0_12"));
        lineEdit_v0_12->setGeometry(QRect(40, 90, 71, 20));
        label_133 = new QLabel(gbox_meter_12);
        label_133->setObjectName(QString::fromUtf8("label_133"));
        label_133->setGeometry(QRect(10, 90, 21, 16));
        label_134 = new QLabel(gbox_meter_12);
        label_134->setObjectName(QString::fromUtf8("label_134"));
        label_134->setGeometry(QRect(10, 120, 21, 16));
        label_135 = new QLabel(gbox_meter_12);
        label_135->setObjectName(QString::fromUtf8("label_135"));
        label_135->setGeometry(QRect(120, 60, 21, 16));
        label_136 = new QLabel(gbox_meter_12);
        label_136->setObjectName(QString::fromUtf8("label_136"));
        label_136->setGeometry(QRect(120, 90, 21, 16));
        label_137 = new QLabel(gbox_meter_12);
        label_137->setObjectName(QString::fromUtf8("label_137"));
        label_137->setGeometry(QRect(120, 120, 21, 16));
        lineEdit_e1_12 = new QLineEdit(gbox_meter_12);
        lineEdit_e1_12->setObjectName(QString::fromUtf8("lineEdit_e1_12"));
        lineEdit_e1_12->setGeometry(QRect(40, 120, 71, 20));
        label_138 = new QLabel(gbox_meter_12);
        label_138->setObjectName(QString::fromUtf8("label_138"));
        label_138->setGeometry(QRect(120, 150, 21, 16));
        lineEdit_v1_12 = new QLineEdit(gbox_meter_12);
        lineEdit_v1_12->setObjectName(QString::fromUtf8("lineEdit_v1_12"));
        lineEdit_v1_12->setGeometry(QRect(40, 150, 71, 20));
        label_139 = new QLabel(gbox_meter_12);
        label_139->setObjectName(QString::fromUtf8("label_139"));
        label_139->setGeometry(QRect(10, 150, 21, 16));
        lineEdit_err_12 = new QLineEdit(gbox_meter_12);
        lineEdit_err_12->setObjectName(QString::fromUtf8("lineEdit_err_12"));
        lineEdit_err_12->setEnabled(false);
        lineEdit_err_12->setGeometry(QRect(40, 180, 41, 20));
        label_140 = new QLabel(gbox_meter_12);
        label_140->setObjectName(QString::fromUtf8("label_140"));
        label_140->setGeometry(QRect(10, 180, 21, 16));
        label_141 = new QLabel(gbox_meter_12);
        label_141->setObjectName(QString::fromUtf8("label_141"));
        label_141->setGeometry(QRect(100, 180, 21, 16));

        retranslateUi(CmbVerifyClass);

        QMetaObject::connectSlotsByName(CmbVerifyClass);
    } // setupUi

    void retranslateUi(QWidget *CmbVerifyClass)
    {
        CmbVerifyClass->setWindowTitle(QApplication::translate("CmbVerifyClass", "Combine Verify", 0, QApplication::UnicodeUTF8));
        label_208->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p><span style=\" color:#0000ff;\">Please select the Unit, Install position </span></p><p><span style=\" color:#0000ff;\">and minimum temperature difference corectly</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        btnPara->setText(QApplication::translate("CmbVerifyClass", "Para", 0, QApplication::UnicodeUTF8));
        btnExit->setText(QApplication::translate("CmbVerifyClass", "Exit", 0, QApplication::UnicodeUTF8));
        pushButton_5->setText(QApplication::translate("CmbVerifyClass", "Start", 0, QApplication::UnicodeUTF8));
        pushButton_6->setText(QApplication::translate("CmbVerifyClass", "Save", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt; font-weight:600; color:#0000ff;\">Data</span></p></body></html>", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("CmbVerifyClass", "Install Pos", 0, QApplication::UnicodeUTF8));
        rbtn_pos_in->setText(QApplication::translate("CmbVerifyClass", "In", 0, QApplication::UnicodeUTF8));
        rbtn_pos_out->setText(QApplication::translate("CmbVerifyClass", "Out", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("CmbVerifyClass", "Unit", 0, QApplication::UnicodeUTF8));
        rbtn_unit_kwh->setText(QApplication::translate("CmbVerifyClass", "kWh", 0, QApplication::UnicodeUTF8));
        rbtn_unit_mj->setText(QApplication::translate("CmbVerifyClass", "MJ", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("CmbVerifyClass", "Min \316\230", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>\316\224\316\270min</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>K</p></body></html>", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("CmbVerifyClass", "standard temperature sensor", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>In</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>\316\251</p></body></html>", 0, QApplication::UnicodeUTF8));
        btn_collection->setText(QApplication::translate("CmbVerifyClass", "collect", 0, QApplication::UnicodeUTF8));
        btn_stop->setText(QApplication::translate("CmbVerifyClass", "stop", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>\342\204\203</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>\342\204\203</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>\316\251</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Out</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_1->setTitle(QApplication::translate("CmbVerifyClass", "1", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_2->setTitle(QApplication::translate("CmbVerifyClass", "2", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_3->setTitle(QApplication::translate("CmbVerifyClass", "3", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_4->setTitle(QApplication::translate("CmbVerifyClass", "4", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_5->setTitle(QApplication::translate("CmbVerifyClass", "5", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_55->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_56->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_57->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_58->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_59->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_60->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_61->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_62->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_63->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_64->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_6->setTitle(QApplication::translate("CmbVerifyClass", "6", 0, QApplication::UnicodeUTF8));
        label_65->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_66->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_67->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_68->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_69->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_70->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_71->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_72->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_73->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_74->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_75->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_7->setTitle(QApplication::translate("CmbVerifyClass", "7", 0, QApplication::UnicodeUTF8));
        label_76->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_77->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_78->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_79->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_80->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_81->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_82->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_83->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_84->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_85->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_86->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_8->setTitle(QApplication::translate("CmbVerifyClass", "8", 0, QApplication::UnicodeUTF8));
        label_87->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_88->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_89->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_90->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_91->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_92->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_93->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_94->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_95->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_96->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_97->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_9->setTitle(QApplication::translate("CmbVerifyClass", "9", 0, QApplication::UnicodeUTF8));
        label_98->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_99->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_100->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_101->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_102->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_103->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_104->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_105->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_106->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_107->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_108->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_10->setTitle(QApplication::translate("CmbVerifyClass", "10", 0, QApplication::UnicodeUTF8));
        label_109->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_110->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_111->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_112->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_113->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_114->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_115->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_116->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_117->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_118->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_119->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_11->setTitle(QApplication::translate("CmbVerifyClass", "11", 0, QApplication::UnicodeUTF8));
        label_120->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_121->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_122->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_123->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_124->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_125->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_126->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_127->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_128->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_129->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_130->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
        gbox_meter_12->setTitle(QApplication::translate("CmbVerifyClass", "12", 0, QApplication::UnicodeUTF8));
        label_131->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>Sn</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_132->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_133->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V0</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_134->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">E1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_135->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_136->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_137->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>kWh</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_138->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>L</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_139->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">V1</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_140->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p align=\"right\">\316\264</p></body></html>", 0, QApplication::UnicodeUTF8));
        label_141->setText(QApplication::translate("CmbVerifyClass", "<html><head/><body><p>%</p></body></html>", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class CmbVerifyClass: public Ui_CmbVerifyClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CMBVERIFY_H
